<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Daemon Token
    |--------------------------------------------------------------------------
    | Shared secret used to authenticate requests to the Go daemon's TCP port.
    | Generated by `spikster install` and stored in /etc/spikster/daemon.token.
    | Injected into .env by go.sh as DAEMON_TOKEN.
    */
    'daemon_token' => env('DAEMON_TOKEN', ''),

    /*
    |--------------------------------------------------------------------------
    | Default PHP version
    |--------------------------------------------------------------------------
    */
    'default_php' => env('SPIKSTER_DEFAULT_PHP', '8.3'),

    /*
    |--------------------------------------------------------------------------
    | Users prefix
    |--------------------------------------------------------------------------
    | Prefix for generated system usernames (e.g. "sp" → spAbcd1234).
    */
    'users_prefix' => env('SPIKSTER_USERS_PREFIX', 'sp'),

];
