<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Daemon Token
    |--------------------------------------------------------------------------
    | Shared secret used to authenticate requests to the Go daemon's TCP port.
    | Generated by `spikster install` and stored in /etc/spikster/daemon.token.
    | Injected into .env by go.sh as DAEMON_TOKEN.
    */
    'daemon_token' => env('SPIKSTER_DAEMON_TOKEN', env('DAEMON_TOKEN', '')),

    /*
    |--------------------------------------------------------------------------
    | Default PHP version
    |--------------------------------------------------------------------------
    */
    'default_php' => env('SPIKSTER_DEFAULT_PHP', '8.3'),

    /*
    |--------------------------------------------------------------------------
    | Users prefix
    |--------------------------------------------------------------------------
    | Prefix for generated system usernames (e.g. "sp" → spAbcd1234).
    */
    'users_prefix' => env('SPIKSTER_USERS_PREFIX', 'sp'),

    /*
    |--------------------------------------------------------------------------
    | Supported PHP versions
    |--------------------------------------------------------------------------
    */
    'phpvers' => ['8.4', '8.3', '8.2', '8.1', '8.0', '7.4'],

    /*
    |--------------------------------------------------------------------------
    | Allowed services for restart/stop/start
    |--------------------------------------------------------------------------
    */
    'services' => ['nginx', 'php', 'mysql', 'redis', 'supervisor'],

    /*
    |--------------------------------------------------------------------------
    | Database root password
    |--------------------------------------------------------------------------
    | MySQL root password used by the Go daemon for CREATE DATABASE operations.
    | Falls back to the Laravel DB password for environments where spikster
    | and root share the same credentials (go.sh setup).
    */
    'db_root_pass' => env('DB_ROOT_PASS', ''),

];
