<?php

namespace App\Http\Controllers;

use App\Models\Server;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 * ShellController
 *
 * Serves shell scripts for server setup and site operations.
 * Scripts are stored in storage/app/spikster/ (previously cipi/).
 */
class ShellController extends Controller
{
    /**
     * Server setup script (bootstrap a fresh VPS).
     *
     * Only serves servers that have not been provisioned yet (status 0).
     * The route is protected by a signed, expiring URL generated by the
     * panel API — see ServerController::create().
     */
    public function setup(string $server_id)
    {
        $server = Server::where('server_id', $server_id)->where('status', 0)->firstOrFail();

        $script = Storage::get('spikster/setup.sh');
        $script = Str::replaceArray('???', [
            $server->password,
            $server->database,
            $server->server_id,
        ], $script);

        return response($script)->withHeaders(['Content-Type' => 'application/x-sh']);
    }
}
